#if !canImport(ObjectiveC)
import XCTest

extension CommandExampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandExampleTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommandExampleTests.__allTests__CommandExampleTests),
    ]
}
#endif
